server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/nyayhelp_auth
spring.datasource.username=root
spring.datasource.password=Star@1857

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

nyayhelp.notificationservice.url=${NOTIFICATIONSERVICE_URL:http://localhost:8086}
nyayhelp.admin.email=${ADMIN_EMAIL:}