server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/nyayhelp_auth
spring.datasource.username=root
spring.datasource.password=Star@1857

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


